### ISSUE TITLE
Ethiopia civ

### ISSUE THREAD

**Issue by RayhanSyed** [hosj-IO/civ5rnddrafter#29]
Hi, 
I liked your draft picker a lot because it includes which pack of civs are allowed which Fruitystrike doesn't have. I just wanted you to know that Ethiopia is included in both G&K And BNW. I don't think it currently includes it in the latter, only the former.
Just wanted you to know.

**Comment by hosj-IO** [comment]
RS-CU, that's correct. I wasn't aware this was possible. I'll add this asap.

**Comment by hosj-IO** [comment]
Spain is also nation with multiple DLC
