### ISSUE TITLE
Civ 6 Leader pass support

### ISSUE THREAD

**Issue by mattcrwi** [hosj-IO/civ5rnddrafter#49]
Will support for the leader pass be added?

**Comment by Ayzrian** [comment]
+1

**Comment by jakezatecky** [comment]
You may consider using my alternative Civ 6 drafter ([website](https://civilizationdrafter.com/), [GitHub](https://github.com/jakezatecky/civ-drafter)). It supports the Leader Pass DLC, and I intend to update the list as new leaders come.

**Comment by hosj-IO** [comment]
Fixed with 62517a24d978fd2d3eccebebac8feec7386010e9
